directories:
  output: dist_electron
  buildResources: build
  app: dist_electron/bundled
files:
  - filter:
      - '**'
extends: null
appId: xhznl-todo-list
productName: xhznl-todo-list
copyright: Copyright © 2020 xhznl
win:
  icon: ./public/logo.ico
  target: nsis
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  shortcutName: xhznl-todo-list
publish:
  - github
electronVersion: 9.3.4
